trigger:
  - master
stages:
  - stage: Build
    jobs:
      - job: build
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              npm ci
              npm run build
            workingDirectory: js
